In [2]:
import numpy as np

In [4]:
t=np.array([8,6,7,4,5])

In [6]:
t.flatten()

array([8, 6, 7, 4, 5])

In [7]:
t[::-1]

array([5, 4, 7, 6, 8])

In [8]:
a = np.array([1,8,9,5])
b= np.array([2,5,6,8])

In [9]:
c = np.concatenate([a,b])

In [10]:
c

array([1, 8, 9, 5, 2, 5, 6, 8])

In [13]:
n=np.array([[2,4,5],[3,5,7]])
m=np.array([[3,5,6],[4,6,9],[2,7,0]])
o=np.concatenate([n,m])
o

array([[2, 4, 5],
       [3, 5, 7],
       [3, 5, 6],
       [4, 6, 9],
       [2, 7, 0]])

In [15]:
x= np.full([2,2],20, dtype= int)
y= np.full([2,2],5, dtype= int)
x

array([[20, 20],
       [20, 20]])

In [17]:
x+=y

In [18]:
x

array([[30, 30],
       [30, 30]])

In [19]:
x-y

array([[25, 25],
       [25, 25]])

In [20]:
x*y

array([[150, 150],
       [150, 150]])

In [21]:
x/y

array([[6., 6.],
       [6., 6.]])

In [22]:
y.min()

5

In [23]:
x.mean()

30.0

In [24]:
d = np.std(y)

In [25]:
d

0.0

In [26]:
y.T

array([[5, 5],
       [5, 5]])