In [1]:
import numpy as np

In [2]:
my1DArray = np.array([9,8,7,6])
print(my1DArray.ndim)

1


In [6]:
my2DArray = np.array([[9,8,7,6], [6,8,9,5], [3,8,7,10]])
print(my2DArray.ndim)

2


In [7]:
my3DArray = np.array([[[9,8,7,6],[6,8,9,5]],[[5,6,8,9],[12,15,23,18]]])
print(my3DArray.ndim)

3


In [10]:
a = np.arange(5,100,5)

In [11]:
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [20]:
b= np.linspace(1,10,5, dtype=int)

In [21]:
b

array([ 1,  3,  5,  7, 10])

In [31]:
c= np.random.randint(1000,size=(10,7),dtype=int)

In [32]:
c

array([[277, 883, 824, 177, 865, 577, 743],
       [634, 870, 943, 220, 265, 208, 607],
       [996, 876, 205,  81, 218, 877, 468],
       [315, 859, 779, 241, 749, 554, 159],
       [264, 162, 189, 954,  35, 404,  94],
       [ 26,  66, 602, 712, 661, 991, 636],
       [966, 109, 221, 566, 804, 747, 505],
       [250, 299, 665, 905, 126, 664, 964],
       [897, 191, 109, 681, 911,  47, 232],
       [989, 908, 233, 453, 402, 704, 975]])

In [35]:
d= np.random.randint(10000,size=(10,30),dtype=int)

In [36]:
d

array([[3240, 3143, 4991, 9490, 2382, 5760, 1733, 5526, 3416, 7939, 3093,
         484, 7261,  566, 3015, 6266, 5492, 6855, 6137, 4664, 6669, 6743,
        2003, 7745, 8958, 5650, 8284,  315, 6551, 5558],
       [2065, 1122, 6388, 6867, 1182, 6280, 6929,  721, 8784, 5164, 3891,
        1226, 9171, 6068, 7666, 4215, 5671, 5626,  778, 9924, 5746, 9744,
        4683, 1307, 7825, 9779, 3923,  760, 1625, 5042],
       [ 211, 7814, 2795, 7153, 5927, 5313, 9571, 9577,  637, 7293, 2840,
        5056, 3224, 3989, 8982, 9388, 1689, 2461, 8551, 3330, 2549, 7395,
         132, 8695, 4536, 7667,   96,  659, 8453, 5122],
       [8380, 9890, 5010, 1231, 1215, 4679, 1517, 6240, 3798, 4001, 7155,
        6552, 6395, 4790, 2315, 1759, 8143, 8484, 5588,  734, 1969, 7097,
        9057, 3717, 5046, 2272, 9286, 9984, 3082, 9753],
       [3123, 1874, 5512, 1573,  397,  974, 8342, 9550, 7796, 1338,   81,
        7482, 1671, 2547, 6311, 2997, 7189, 4373, 3138, 2447, 3849, 6019,
        5526, 4191, 7345, 3064, 

In [38]:
e=np.empty((3,2))

In [39]:
e

array([[4.75747065e-310, 0.00000000e+000],
       [6.69617801e-310, 6.69624361e-310],
       [6.69624365e-310, 6.69624361e-310]])

In [40]:
d[1:3,2:4]

array([[6388, 6867],
       [2795, 7153]])

In [44]:
d[1:4,4:5]

array([[1182],
       [5927],
       [1215]])